var demo = document.querySelector(".indicators1");
demo.style.width = "1150px";
demo.style.height = "400px";
demo.style.backgroundColor = "#FFF0E2";
demo.style.marginTop = "62px";
demo.style.borderRadius = "15px";
demo.style.border = "2px solid #FFE9D6 ";
var bablu = document.querySelector(".bablu");
bablu.style.width = "400px";
bablu.style.height = "200px";
bablu.style.marginTop = "52px";
bablu.style.marginLeft = "22px";
var sidebox = document.querySelector(".sidebox");
sidebox.style.width = "550px"
sidebox.style.height = "460px"
sidebox.style.backgroundColor = "white";
sidebox.style.borderRadius = "15px"
sidebox.style.border = "1px solid rgba(113, 106, 147, .2)";
var sixteenbox = document.querySelector(".sixteenbox")
sixteenbox.style.width = "1200px";
sixteenbox.style.height = "300px";
sixteenbox.style.marginLeft = "8%"
sixteenbox.style.marginBottom = "3%"
var bubby = document.querySelector(".bubby")
bubby.style.width = "1100px"
bubby.style.height = "400px"
bubby.style.marginLeft = "9%"
bubby.style.marginTop = "2%"
const ninjas = document.querySelector(".ninjas")
ninjas.style.width = "780px"
ninjas.style.height = "400px"
var thamil = document.querySelector(".interviewsection");
thamil.style.width = "1100px"
thamil.style.height = "350px"
thamil.style.marginLeft = "9%"
thamil.style.marginTop = "3%"
thamil.style.marginBottom = "3%"
thamil.style.borderRadius="15px"
thamil.style.border = "1px solid  rgba(255, 166, 0, 0.432)";
thamil.style.backgroundColor = "#FFF0E2";
var accelerate=document.querySelector(".accelerate")
accelerate.style.marginLeft="9%"
accelerate.style.marginBottom = "5%"
accelerate.style.margintop="6%"
accelerate.style.width = "1100px"
accelerate.style.height = "200px"
accelerate.style.backgroundColor= ""
accelerate.style.borderRadius="15px"
accelerate.style.border = "1px solid rgba(113, 106, 147, .2)";
accelerate.style.boxShadow=" 5px 5px 3px rgba(113, 106, 147, .2)";
var recruiter=document.querySelector(".recruiter")
recruiter.style.marginLeft="9%"
recruiter.style.margintop="6%"
recruiter.style.width = "1100px"
recruiter.style.height = "350px"
recruiter.style.marginBottom = "5%"
var footer=document.querySelector(".footer")
footer.style.marginLeft="9%"
var footerpage=document.querySelector(".footerpage")
footerpage.style.marginLeft="9%"